



import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author HP
 */
public class AddNurse extends javax.swing.JFrame {
                JFrame frame;
    /**
     * Creates new form AddNurse
     */
    Connection conn = null;
    
    public AddNurse() {
        super("AddNurse");
        initComponents();
        conn = Databaseconnection.connection();
    }
    
            public void reset(){
                    jTextField1.setText("");
            jTextField2.setText("");
            jTextField3.setText("");
            jTextField4.setText("");
            jTextField5.setText("");
            jTextField6.setText("");
            jTextField7.setText("");
            jTextField8.setText("");
            jTextField9.setText("");
            jTextField10.setText("");       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

         frame=new JFrame("AddNurse");
        jPanel1 = new javax.swing.JPanel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();
        jTextField7 = new javax.swing.JTextField();
        jTextField8 = new javax.swing.JTextField();
        jTextField9 = new javax.swing.JTextField();
        jTextField10 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

//        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
//
//        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());


        frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        frame.setAlwaysOnTop(true);
        frame.setLocation(50, 50);
        frame.setSize(1000,710);
        frame.setLayout(null);
 
        jTextField1.setBounds(250, 120, 190, 30);
        frame.add(jTextField1);
        jTextField2.setBounds(250, 159, 190, 30);
        frame.add(jTextField2);
        jTextField3.setBounds(250, 209, 190, 30);
        frame.add(jTextField3);
        jTextField4.setBounds(250, 260, 190, 30);
        frame.add(jTextField4);
        jTextField5.setBounds(250, 310, 190, 30);
        frame.add(jTextField5);
        jTextField6.setBounds(260, 360, 180, 30);
        frame.add(jTextField6);
        jTextField7.setBounds(260, 410, 180, 30);
        frame.add(jTextField7);
        jTextField8.setBounds(260, 460, 180, 30);
        frame.add(jTextField8);
        jTextField9.setBounds(290, 510, 150, 30);
        frame.add(jTextField9);
        jTextField10.setBounds(500, 400, 290, 140);
        frame.add(jTextField10);

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("Pic/add.png"))); // NOI18N
        jButton1.setText("jButton1");
        jButton1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 60, 153), 0));
        jButton1.addActionListener(this::jButton1ActionPerformed);
        jButton1.setBounds(230, 590, 250, 60);
        frame.add(jButton1);

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("Pic/backpt2.png"))); // NOI18N
        jButton2.setText("jButton2");
        jButton2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 60, 153), 0));
        jButton2.addActionListener(this::jButton2ActionPerformed);
        jButton2.setBounds(550, 590, 240, 60);
        frame.add(jButton2);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("Pic/animation_300_lhza8kd4.gif"))); // NOI18N
        jLabel1.setText("jLabel1");
        jLabel1.setBounds(540, 90, 300, 240);
        frame.add(jLabel1);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("Pic/HMSnurseadd.jpg"))); // NOI18N
        jLabel2.setText("jLabel2");
        jLabel2.setBounds(0, 0, 1000, 710);
        frame.add(jLabel2);

//        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
//        getContentPane().setLayout(layout);
//        layout.setHorizontalGroup(
//            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
//            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
//        );
//        layout.setVerticalGroup(
//            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
//            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
//        );

        pack();
        frame.setVisible(true);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        NurseModule obj = new  NurseModule();
        obj.setVisible(true);
        dispose();
       
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
                        try{
           
           String sql= "insert into nurse values(?,?,?,?,?,?,?,?,?,?)";
            PreparedStatement ptst=conn.prepareCall(sql);
                if (jTextField1.getText().equals("")) {
                JOptionPane.showMessageDialog( frame, "Please enter Nurse's id","Error", JOptionPane.ERROR_MESSAGE);
                return;

            }
            if (jTextField2.getText().equals("")) {
                JOptionPane.showMessageDialog( frame, "Please enter doctor's full name","Error", JOptionPane.ERROR_MESSAGE);
                return;

            }
            if (jTextField3.getText().equals("")) {
                JOptionPane.showMessageDialog( frame, "Please enter Doctor's Email ID","Error", JOptionPane.ERROR_MESSAGE);
                return;
            }
            if (jTextField4.getText().equals("")) {
                JOptionPane.showMessageDialog( frame, "Please enter Contact no","Error", JOptionPane.ERROR_MESSAGE);
                return;
            }
           if (jTextField5.getText().equals("")) {
                JOptionPane.showMessageDialog( frame, "Please enter Address","Error", JOptionPane.ERROR_MESSAGE);
                return;
            }
         
            if (jTextField6.getText().equals("")) {
                JOptionPane.showMessageDialog( frame, "Please enter qualifications","Error", JOptionPane.ERROR_MESSAGE);
                return;
            }
            
              if (jTextField7.getText().equals("")) {
                JOptionPane.showMessageDialog( frame, "Please select gender","Error", JOptionPane.ERROR_MESSAGE);
                return;
            }
            if (jTextField8.getText().equals("")) {
                JOptionPane.showMessageDialog( frame, "Please select blood group","Error", JOptionPane.ERROR_MESSAGE);
                return;
            }
           
            if (jTextField9.getText().equals("")) {
                JOptionPane.showMessageDialog( frame, "Please enter joining date","Error", JOptionPane.ERROR_MESSAGE);
                return;
            }
                     if (jTextField10.getText().equals("")) {
                JOptionPane.showMessageDialog( frame, "Please enter schedule","Error", JOptionPane.ERROR_MESSAGE);
                return;
            }
                     else{
              
            ptst.setString(1,jTextField1.getText());
            ptst.setString(2,jTextField2.getText());
            ptst.setString(3,jTextField3.getText());
            ptst.setString(4,jTextField4.getText());
            ptst.setString(5,jTextField5.getText());
            ptst.setString(6,jTextField6.getText());
            ptst.setString(7,jTextField7.getText());
            ptst.setString(8,jTextField8.getText());
            ptst.setString(9,jTextField9.getText());
            ptst.setString(10,jTextField10.getText());
            
            ptst.executeUpdate();
            JOptionPane.showMessageDialog(frame, "Data Added Successfully");
          
            reset();
                     }
            
        }
        catch(Exception e){
        JOptionPane.showMessageDialog(frame, e);
        }
        
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        new AddNurse();
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddNurse.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddNurse.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddNurse.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddNurse.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                  
//            }
//        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField10;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextField9;
    // End of variables declaration//GEN-END:variables
}

