
import javax.swing.JFrame;

 ///*
// * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
// * Click nbfs://nbhost/SystemFileSystem/Templates/Classes/Class.java to edit this template
// */
//


/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Zainab
 */
public class Admin extends javax.swing.JFrame {

    JFrame frame;
     /* Creates new form admin
     */
    public Admin() {
        initComponents();
 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
         
         
         
         frame=new JFrame(" ADMIN");
        jLabel1 = new javax.swing.JLabel();
        NurseModule = new javax.swing.JButton();
        room = new javax.swing.JButton();
        appointment = new javax.swing.JButton();
        DoctorModule = new javax.swing.JButton();
        billing = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        logout = new javax.swing.JMenuItem();
        
        
        
        
        frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        frame.setAlwaysOnTop(true);
        frame.setLocation(50, 50);
        frame.setSize(1135,840);
        frame.setLayout(null);

//        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
//        setLocation(new java.awt.Point(50, 50));
//        setMinimumSize(new java.awt.Dimension(500, 500));

//        jPanel1.setLayout(null);
//        jPanel1.setSize(800,400);
//        jPanel1.setLocation(50,50);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/admin.gif"))); // NOI18N
        jLabel1.setBounds(0, -40, 1135, 840);
        frame.add(jLabel1);

        NurseModule.setText("nurseview");
        NurseModule.addActionListener(this::NurseModuleActionPerformed);
        NurseModule.setBounds(220, 630, 210, 50);
        frame.add(NurseModule);

        room.setText("room");
        room.addActionListener(this::roomActionPerformed);
        room.setBounds(650, 630, 210, 50);
        frame.add(room);

        appointment.setText("appointment");
        appointment.addActionListener(this::appointmentActionPerformed);
        appointment.setBounds(890, 580, 210, 50);
        frame.add(appointment);

        DoctorModule.setText("doctorview");
        DoctorModule.addActionListener(this::DoctorModuleActionPerformed);
        DoctorModule.setBounds(10, 580, 210, 50);
        frame.add(DoctorModule);

        billing.setText("appointment");
        billing.addActionListener(this::billingActionPerformed);
           billing.setBounds(440, 710, 210, 50);
        frame.add(billing);

        jMenu1.setText("Home");

        logout.setIcon(new javax.swing.ImageIcon(getClass().getResource("Pic/logout.png"))); // NOI18N
        logout.setText("Home");
        logout.addActionListener(this::logoutActionPerformed);
        jMenu1.add(logout);
        
        jMenuBar1.add(jMenu1);

        frame.setJMenuBar(jMenuBar1);

//        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
//        getContentPane().setLayout(layout);
//        layout.setHorizontalGroup(
//            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
//            .addComponent(frame, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
//        );
//        layout.setVerticalGroup(
//            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
//            .addComponent(frame, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
//        );

        pack();
        frame.setVisible(true);
    }// </editor-fold>//GEN-END:initComponents

    private void logoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        Home obj = new Home();
        obj.setVisible(true);
    }//GEN-LAST:event_logoutActionPerformed

    private void NurseModuleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NurseModuleActionPerformed
        // TODO add your handling code here:
        frame.setVisible(false);
        NurseModule obj = new NurseModule();
        obj.setVisible(true);
    }//GEN-LAST:event_NurseModuleActionPerformed

    private void roomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_roomActionPerformed
        // TODO add your handling code here:
        frame.setVisible(false);
        RoomModule obj = new RoomModule();
        obj.setVisible(true);
    }//GEN-LAST:event_roomActionPerformed

    private void appointmentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_appointmentActionPerformed
        // TODO add your handling code here:
        frame.setVisible(false);
        Appointment obj = new Appointment();
        obj.setVisible(true);
    }//GEN-LAST:event_appointmentActionPerformed

    private void DoctorModuleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DoctorModuleActionPerformed
        // TODO add your handling code here:
        frame.setVisible(false);
        DoctorModule obj=new DoctorModule();
        obj.setVisible(true);
    }//GEN-LAST:event_DoctorModuleActionPerformed

    private void billingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_billingActionPerformed
        // TODO add your handling code here:
        frame.setVisible(false);
        Billing obj = new Billing();
        obj.setVisible(true);
    }//GEN-LAST:event_billingActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        
          new Admin(). setVisible(false); 
           
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                
//                
//            }
//        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton DoctorModule;
    private javax.swing.JButton NurseModule;
    private javax.swing.JButton appointment;
    private javax.swing.JButton billing;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
//    private javax.swing.JPanel jPanel1;
    private javax.swing.JMenuItem logout;
    private javax.swing.JButton room;
    // End of variables declaration//GEN-END:variables
}
