


import java.sql.Connection;
//import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author HP
 */
public class DeleteDoctor extends javax.swing.JFrame {
    JFrame frame;

    /**
     * Creates new form DeleteDoctor
     */
    Connection conn = null;
    public DeleteDoctor() {
        super("DeleteDoctor");
        initComponents();
        conn = Databaseconnection.connection();
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
          frame=new JFrame("Delete Doctor");
//        jPanel1 = new javax.swing.JPanel();
        jTextField1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();

//        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
//
//        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

          frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        frame.setAlwaysOnTop(true);
        frame.setLocation(50, 50);
        frame.setSize(1250,1000);
        frame.setLayout(null);
        
        jTextField1.setBounds(340, 130, 310, 30);
        frame.add(jTextField1);

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("Pic/viewrecord.png"))); // NOI18N
        jButton1.setText("jButton1");
        jButton1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 60, 153), 0));
        jButton1.addActionListener(this::jButton1ActionPerformed);
         jButton1.setBounds(140, 580, 230, 60);
        frame.add(jButton1);

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("Pic/viewallrecords.png"))); // NOI18N
        jButton2.setText("jButton2");
        jButton2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 60, 153), 0));
        jButton2.addActionListener(this::jButton2ActionPerformed);
        jButton2.setBounds(380, 580, 260, 60);
        frame.add(jButton2);

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("Pic/removesmall.png"))); // NOI18N
        jButton3.setText("jButton3");
        jButton3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 60, 153), 0));
        jButton3.addActionListener(this::jButton3ActionPerformed);
          jButton3.setBounds(400, 480, 240, 60);
        frame.add(jButton3);

        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("Pic/backpt2.png"))); // NOI18N
        jButton4.setText("jButton4");
        jButton4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 60, 153), 0));
        jButton4.addActionListener(this::jButton4ActionPerformed);
          jButton4.setBounds(670, 570, 230, 70);
        frame.add(jButton4);

        jTable2.setBackground(new java.awt.Color(204, 255, 255));
        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Doctor ID", "Full Name", "Emain ID", "Contact no", "Address", "Qualification", "Gender", "Blood Group", "Joining Date", "Availability"
            }
        ));
        jScrollPane2.setViewportView(jTable2);
         jScrollPane2.setBounds(50, 220, 900, 250);
        frame.add(jScrollPane2);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("Pic/RemoveDoc.jpg"))); // NOI18N
        jLabel1.setText("jLabel1");
         jLabel1.setBounds(0, 0, 1000, 700);
        frame.add(jLabel1);

//        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
//        getContentPane().setLayout(layout);
//        layout.setHorizontalGroup(
//            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
//            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
//        );
//        layout.setVerticalGroup(
//            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
//            .addGroup(layout.createSequentialGroup()
//                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
//                .addGap(0, 0, Short.MAX_VALUE))
//        );

        pack();
         frame.setVisible(true);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
                String Ddoctor =jTextField1.getText();
                  try{
                
            Statement st = conn.createStatement();
            String sql ="DELETE from `doctor` WHERE `Doctor ID` ="+Ddoctor;
            PreparedStatement ptst=conn.prepareCall(sql);
                                       if(jTextField1.getText().equals("")) {
                JOptionPane.showMessageDialog( frame, "Please enter doctor id","Error", JOptionPane.ERROR_MESSAGE);
                return;

            }
           else{
            ptst.executeUpdate();
            JOptionPane.showMessageDialog(frame,"The Doctor's Records have been deleted");
             jTextField1.setText("");
                                       }
                  }
                  catch(Exception e){
                      JOptionPane.showMessageDialog(frame,e);
                  }
        
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
                  try{
               
            Statement st = conn.createStatement();
            String sql ="select * from doctor";
                PreparedStatement ptst=conn.prepareCall(sql);
                ResultSet rs= ptst.executeQuery();
               DefaultTableModel tm=(DefaultTableModel)jTable2.getModel();
               tm.setRowCount(0);
               while(rs.next()){
               Object o[]={rs.getInt("Doctor ID"),rs.getString("Full Name"),rs.getString("Email ID"),rs.getString("Contact no"),rs.getString("Address"),rs.getString("Qualification"),rs.getString("Gender"),rs.getString("Blood Group"),rs.getString("Date of Joining"),rs.getString("Availability")};
               tm.addRow(o);   
          }
           
          }
          catch(Exception e){
              JOptionPane.showMessageDialog(frame,e);
          
          }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
                  try{
                
            String sql ="select * from doctor";
                PreparedStatement ptst=conn.prepareCall(sql);
                ResultSet rs= ptst.executeQuery();
               DefaultTableModel tm=(DefaultTableModel)jTable2.getModel();
               tm.setRowCount(0);
               while(rs.next()){
                   if(jTextField1.getText().equals(rs.getString("Doctor ID"))){
               Object o[]={rs.getString("Doctor ID"),rs.getString("Full Name"),rs.getString("Email ID"),rs.getString("Contact no"),rs.getString("Address"),rs.getString("Qualification"),rs.getString("Gender"),rs.getString("Blood Group"),rs.getString("Date of Joining"),rs.getString("Availability")};
               tm.addRow(o);   
               } 
          }
           
          }
          catch(Exception e){
              JOptionPane.showMessageDialog(frame,e);
          
          }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        DoctorModule obj = new DoctorModule();
        obj.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        
        new DeleteDoctor();
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DeleteDoctor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DeleteDoctor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DeleteDoctor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DeleteDoctor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                 
//            }
//        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable2;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables

    /**
     *
     * @param b
     */
//    @Override
//    public void setVisible(boolean b) {
//        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
//    }
}
