
import javax.swing.JFrame;
//import javax.swing.JPanel;

// import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
/**
 *
 * @author DELL
 */
public class Home extends javax.swing.JFrame {

    JFrame frame;

    /**
     * Creates new form home
     */
    public Home() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        frame = new JFrame("Hay");
//        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        doctor_ = new javax.swing.JButton();
        nurse_ = new javax.swing.JButton();
        admin_ = new javax.swing.JButton();
        pharmacy_ = new javax.swing.JButton();
        logout_ = new javax.swing.JButton();

        frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        frame.setAlwaysOnTop(true);
        frame.setLocation(50, 50);
        frame.setSize(1135, 840);

        frame.setLayout(null);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("Pic/home1.jpg"))); // NOI18N
        jLabel1.setText("jLabel1");
        jLabel1.setBounds(0, -6, 1120, 780);
        frame.add(jLabel1);

        doctor_.setBackground(new java.awt.Color(0, 102, 204));
        doctor_.setFont(new java.awt.Font("Artifakt Element Black", 0, 18)); // NOI18N
        doctor_.setForeground(new java.awt.Color(255, 255, 255));
        doctor_.setText("doctor");
        doctor_.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        doctor_.addActionListener(this::doctor_ActionPerformed);
        doctor_.setBounds(310, 550, 210, 50);
        frame.add(doctor_);

        nurse_.setBackground(new java.awt.Color(0, 102, 204));
        nurse_.setFont(new java.awt.Font("Artifakt Element Black", 0, 18)); // NOI18N
        nurse_.setForeground(new java.awt.Color(255, 255, 255));
        nurse_.setText("nurse");
        nurse_.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        nurse_.addActionListener(this::nurse_ActionPerformed);
        nurse_.setBounds(600, 550, 230, 50);
        frame.add(nurse_);

        admin_.setBackground(new java.awt.Color(0, 102, 204));
        admin_.setFont(new java.awt.Font("Artifakt Element Black", 0, 18)); // NOI18N
        admin_.setForeground(new java.awt.Color(255, 255, 255));
        admin_.setText("admin");
        admin_.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        admin_.addActionListener(this::admin_ActionPerformed);
        admin_.setBounds(30, 550, 220, 50);
        frame.add(admin_);

        pharmacy_.setBackground(new java.awt.Color(0, 102, 204));
        pharmacy_.setFont(new java.awt.Font("Artifakt Element Black", 0, 18)); // NOI18N
        pharmacy_.setForeground(new java.awt.Color(255, 255, 255));
        pharmacy_.setText("pharmacy");
        pharmacy_.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        pharmacy_.addActionListener(this::pharmacy_ActionPerformed);
        pharmacy_.setBounds(870, 550, 230, 50);
        frame.add(pharmacy_);

        logout_.setBackground(new java.awt.Color(0, 102, 204));
        logout_.setFont(new java.awt.Font("Artifakt Element Black", 0, 18)); // NOI18N
        logout_.setForeground(new java.awt.Color(255, 255, 255));
        logout_.setText("logout");
        logout_.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        logout_.addActionListener(this::logout_ActionPerformed);
        logout_.setBounds(470, 700, 230, 50);
        frame.add(logout_);

//        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
//        getContentPane().setLayout(layout);
//        layout.setHorizontalGroup(
//            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
//            .addComponent(frame, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
//        );
//        layout.setVerticalGroup(
//            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
//            .addComponent(frame, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
//        );
        pack();
        frame.setVisible(true);
    }// </editor-fold>//GEN-END:initComponents

    private void logout_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logout_ActionPerformed
        // TODO add your handling code here:

        frame.setVisible(false);
        new Welcome().setVisible(true);

    }//GEN-LAST:event_logout_ActionPerformed

    private void admin_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_admin_ActionPerformed
        // TODO add your handling code here:
        frame.setVisible(false);
        new Login().setVisible(true);
        dispose();
    }//GEN-LAST:event_admin_ActionPerformed

    private void doctor_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_doctor_ActionPerformed
        // TODO add your handling code here:
        frame.setVisible(false);
        new Login().setVisible(true);
        dispose();
    }//GEN-LAST:event_doctor_ActionPerformed

    private void nurse_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nurse_ActionPerformed
        frame.setVisible(false);
        new Login().setVisible(true);
        dispose();
    }//GEN-LAST:event_nurse_ActionPerformed

    private void pharmacy_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pharmacy_ActionPerformed
        frame.setVisible(false);
        new Login().setVisible(true);
        dispose();
    }//GEN-LAST:event_pharmacy_ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {

        Home home = new Home();
        home.setVisible(false);
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                 
//            }
//        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton admin_;
    private javax.swing.JButton doctor_;
    private javax.swing.JLabel jLabel1;
//    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton logout_;
    private javax.swing.JButton nurse_;
    private javax.swing.JButton pharmacy_;
    // End of variables declaration//GEN-END:variables
}
