///*
// * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
// * Click nbfs://nbhost/SystemFileSystem/Templates/Classes/Class.java to edit this template
// */
//
///**
// *
// * @author PC
// */
//public class Patient {
//
//    public Patient() {
//    }
//
//    void setVisible(boolean b) {
//        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
//    }
//    
//}





import javax.swing.JOptionPane;
import java.sql.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;





/**
 *
 * @author DELL
 */
public class Patient extends javax.swing.JFrame {
    JFrame frame;
    //Statement st;
    Connection con=null;
    ResultSet rs;
    PreparedStatement pst;
    public void reset(){
            id.setText("");
            name.setText("");
            f_name.setText("");
            address.setText("");
            contact.setText("");
            age.setText("");
            days.setText("");
            instructions.setText("");      
    }
    /**
     * Creates new form patient
     */
    public Patient() {
        super("Patient");
        initComponents();
        con = Databaseconnection.connection();
        
        try {
            connect();
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Patient.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(Patient.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    public final void connect() throws ClassNotFoundException, SQLException{
        
        pst=con.prepareStatement("Select * from p");
        //Statement st= con.createStatement(ResultSet.TYPE_SCROLL_SENSITIVE,ResultSet.CONCUR_READ_ONLY);
        rs=pst.executeQuery();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        frame=new JFrame("Patient");
        jPanel1 = new javax.swing.JPanel();
        days = new javax.swing.JTextField();
        blood_grp = new javax.swing.JComboBox<>();
        gender = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        instructions = new javax.swing.JTextArea();
        age = new javax.swing.JTextField();
        contact = new javax.swing.JTextField();
        address = new javax.swing.JTextField();
        f_name = new javax.swing.JTextField();
        name = new javax.swing.JTextField();
        id = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        p_update_ = new javax.swing.JButton();
        p_save_ = new javax.swing.JButton();
        p_delete_ = new javax.swing.JButton();
        p_search_ = new javax.swing.JButton();
        back_ = new javax.swing.JButton();
        close_ = new javax.swing.JButton();

//        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
//        setTitle("DoctorView");
//        setLocation(new java.awt.Point(0, 0));
//        setMinimumSize(new java.awt.Dimension(500, 500));
//        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());


        frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        frame.setAlwaysOnTop(true);
        frame.setLocation(0, 0);
        frame.setSize(1120,800);
        frame.setLayout(null);

//        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());


        days.setFont(new java.awt.Font("Artifakt Element Black", 0, 14)); // NOI18N
        days.setBounds(350, 450, 100, 40);
        frame.add(days);

        blood_grp.setFont(new java.awt.Font("Artifakt Element Black", 0, 14)); // NOI18N
        blood_grp.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "AB+", "AB-", "B+", "B-", "O-", "O+", "A+", "A-" }));
        blood_grp.setBounds(350, 500, 90, 30);
        frame.add(blood_grp);

        gender.setFont(new java.awt.Font("Artifakt Element Black", 0, 14)); // NOI18N
        gender.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Male", "Female", "Other" }));
        gender.setBounds(350, 410, 88, 30);
        frame.add(gender);

        instructions.setColumns(20);
        instructions.setFont(new java.awt.Font("Artifakt Element Black", 0, 14)); // NOI18N
        instructions.setRows(5);
        jScrollPane1.setViewportView(instructions);
        jScrollPane1.setBounds(140, 590, 630, 120);
        frame.add(jScrollPane1);

        
        age.setFont(new java.awt.Font("Artifakt Element Black", 0, 14)); // NOI18N
         age.setBounds(350, 370, 90, 30);
        frame.add(age);

        contact.setFont(new java.awt.Font("Artifakt Element Black", 0, 14)); // NOI18N
        contact.setBounds(350, 320, 220, 40);
        frame.add(contact);

        address.setFont(new java.awt.Font("Artifakt Element Black", 0, 14)); // NOI18N
         address.setBounds(350, 270, 360, 40);
        frame.add(address);

        f_name.setFont(new java.awt.Font("Artifakt Element Black", 0, 14)); // NOI18N
          f_name.setBounds(350, 222, 250, 40);
        frame.add(f_name);

        name.setFont(new java.awt.Font("Artifakt Element Black", 0, 14)); // NOI18N
        name.setBounds(350, 170, 240, 40);
        frame.add(name);

        id.setFont(new java.awt.Font("Artifakt Element Black", 0, 14)); // NOI18N
         id.setBounds(350, 120, 110, 40);
        frame.add(id);

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("Pic/ppp.jpg"))); // NOI18N
        jLabel6.setText("jLabel6");
        jLabel6.setBounds(20, 40, 1120, 770);
        frame.add(jLabel6);

        p_update_.setBackground(new java.awt.Color(0, 102, 204));
        p_update_.setFont(new java.awt.Font("Artifakt Element Black", 0, 14)); // NOI18N
        p_update_.setForeground(new java.awt.Color(255, 255, 255));
        p_update_.setText("update");
        p_update_.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        p_update_.addActionListener(this::p_update_ActionPerformed);
        p_update_.setBounds(870, 330, 190, 50);
        frame.add(p_update_);

        p_save_.setBackground(new java.awt.Color(0, 102, 204));
        p_save_.setFont(new java.awt.Font("Artifakt Element Black", 0, 14)); // NOI18N
        p_save_.setForeground(new java.awt.Color(255, 255, 255));
        p_save_.setText("save");
        p_save_.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        p_save_.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        p_save_.addActionListener(this::p_save_ActionPerformed);
        p_save_.setBounds(880, 260, 170, 40);
        frame.add(p_save_);

        p_delete_.setBackground(new java.awt.Color(0, 102, 204));
        p_delete_.setFont(new java.awt.Font("Artifakt Element Black", 0, 14)); // NOI18N
        p_delete_.setForeground(new java.awt.Color(242, 242, 242));
        p_delete_.setText("delete");
        p_delete_.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        p_delete_.addActionListener(this::p_delete_ActionPerformed);
        p_delete_.setBounds(883, 410, 170, 40);
        frame.add(p_delete_);

        p_search_.setBackground(new java.awt.Color(0, 102, 204));
        p_search_.setFont(new java.awt.Font("Artifakt Element Black", 0, 14)); // NOI18N
        p_search_.setForeground(new java.awt.Color(242, 242, 242));
        p_search_.setText("search");
        p_search_.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        p_search_.addActionListener(this::p_search_ActionPerformed);
         p_search_.setBounds(890, 490, 160, 40);
        frame.add(p_search_);

        back_.setBackground(new java.awt.Color(0, 102, 204));
        back_.setFont(new java.awt.Font("Artifakt Element Black", 0, 14)); // NOI18N
        back_.setForeground(new java.awt.Color(242, 242, 242));
        back_.setText("back");
        back_.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        back_.addActionListener(this::back_ActionPerformed);
        back_.setBounds(890, 560, 160, 50);
        frame.add(back_);

        close_.setBackground(new java.awt.Color(0, 102, 204));
        close_.setFont(new java.awt.Font("Artifakt Element Black", 0, 14)); // NOI18N
        close_.setForeground(new java.awt.Color(242, 242, 242));
        close_.setText("close");
        close_.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        close_.addActionListener(this::close_ActionPerformed);
         close_.setBounds(890, 640, 160, 40);
        frame.add(close_);
 
//        frame.setBounds(-20, -40, 1140, 810);
//        getContentPane().add(frame);

        pack();
//        setLocationRelativeTo(null);
        frame.setVisible(true);
    }// </editor-fold>//GEN-END:initComponents

    private void back_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_back_ActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        new Home().setVisible(true);
    }//GEN-LAST:event_back_ActionPerformed

    private void close_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_close_ActionPerformed
        // TODO add your handling code here:
        int a =JOptionPane.showConfirmDialog(frame,"Do u really want to close","Select",JOptionPane.YES_NO_OPTION);
        if (a==0){
            System.exit(0);
        }
    }//GEN-LAST:event_close_ActionPerformed

    private void p_save_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_p_save_ActionPerformed
        try {
            // TODO add your handling code here:
            pst=con.prepareStatement("insert into p(id,name,f_name,address,contact,age,gender,days,blood,instructions)values(?,?,?,?,?,?,?,?,?,?)");
            pst.setString(1,id.getText());
            pst.setString(2,name.getText());
            pst.setString(3,f_name.getText());
            pst.setString(4,address.getText());
            pst.setString(5,contact.getText());
            pst.setString(6,age.getText());
            pst.setString(7, (String) gender.getSelectedItem());
            pst.setString(8,days.getText());
            pst.setString(9, (String) blood_grp.getSelectedItem());
            pst.setString(10,instructions.getText());
            pst.executeUpdate();
            JOptionPane.showMessageDialog(frame,"success");
        } catch (SQLException ex) {
            Logger.getLogger(Patient.class.getName()).log(Level.SEVERE, null, ex);
        }
        reset();
    }//GEN-LAST:event_p_save_ActionPerformed

    private void p_delete_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_p_delete_ActionPerformed
        try {
            // TODO add your handling code here:
            pst=con.prepareStatement("delete from p where id=?");
            pst.setString(1,id.getText());
            pst.executeUpdate();
            JOptionPane.showMessageDialog(frame,"success");
        } catch (SQLException ex) {
            Logger.getLogger(Patient.class.getName()).log(Level.SEVERE, null, ex);
        }
        reset();
    }//GEN-LAST:event_p_delete_ActionPerformed

    private void p_update_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_p_update_ActionPerformed

            try {
               pst = con.prepareStatement("UPDATE p SET name=?, f_name=?, address=?, contact=?, age=?, gender=?, days=?, blood=?, instructions=? WHERE id=?");
        pst.setString(1, name.getText());
        pst.setString(2, f_name.getText());
        pst.setString(3, address.getText());
        pst.setString(4, contact.getText());
        pst.setString(5, age.getText());
        pst.setString(6, (String) gender.getSelectedItem());
        pst.setString(7, days.getText());
        pst.setString(8, (String) blood_grp.getSelectedItem());
        pst.setString(9, instructions.getText());
        pst.setString(10, id.getText());
        pst.executeUpdate();
        JOptionPane.showMessageDialog(frame, "Update successful");
        } catch (SQLException ex) {
            Logger.getLogger(Patient.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_p_update_ActionPerformed

    private void p_search_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_p_search_ActionPerformed
        try {
            // TODO add your handling code here:
            String s=JOptionPane.showInputDialog(frame,"Enter name for search:");
            pst=con.prepareStatement("select * from p where name=?");
            pst.setString(1,s);
            rs= pst.executeQuery();
           if (rs.next()){
            id.setText(rs.getString(1));
            name.setText(rs.getString(2));
            f_name.setText(rs.getString(3));
            address.setText(rs.getString(4));
            contact.setText(rs.getString(5));
            age.setText(rs.getString(6));
            gender.setSelectedItem(rs.getString(7));
            days.setText(rs.getString(8));
            blood_grp.setSelectedItem(rs.getString(9));
            instructions.setText(rs.getString(10));
            
        }
           else{
               JOptionPane.showMessageDialog(frame, "No record found :(");
           }
            
        } catch (SQLException ex) {
            Logger.getLogger(Patient.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_p_search_ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        new Patient();
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Patient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Patient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Patient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Patient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                 
//            }
//        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField address;
    private javax.swing.JTextField age;
    private javax.swing.JButton back_;
    private javax.swing.JComboBox<String> blood_grp;
    private javax.swing.JButton close_;
    private javax.swing.JTextField contact;
    private javax.swing.JTextField days;
    private javax.swing.JTextField f_name;
    private javax.swing.JComboBox<String> gender;
    private javax.swing.JTextField id;
    private javax.swing.JTextArea instructions;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField name;
    private javax.swing.JButton p_delete_;
    private javax.swing.JButton p_save_;
    private javax.swing.JButton p_search_;
    private javax.swing.JButton p_update_;
    // End of variables declaration//GEN-END:variables
}