
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author HP
 */
public class Patientroom extends javax.swing.JFrame {
          JFrame frame;
    /**
     * Creates new form patientroom
     */
    Connection conn = null;
    public Patientroom() {
       super("patientroom");
        initComponents();
        conn = Databaseconnection.connection();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        
        frame=new JFrame("patientroom");
        jPanel1 = new javax.swing.JPanel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jTextField5 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();

//        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
//
//        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());


         frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        frame.setAlwaysOnTop(true);
        frame.setLocation(50, 50);
        frame.setSize(1000,710);
        frame.setLayout(null);

        jTextField1.setBounds(420, 140, 210, 30);
        frame.add(jTextField1);
        jTextField2.setBounds(420, 190, 210, 30);
        frame.add(jTextField2);
        jTextField3.setBounds(420, 240, 210, 30);
        frame.add(jTextField3);
        jTextField4.setBounds(420, 290, 210, 30);
        frame.add(jTextField4);

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("Pic/admit.png"))); // NOI18N
        jButton1.setText("jButton1");
        jButton1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 0));
        jButton1.addActionListener(this::jButton1ActionPerformed);
         jButton1.setBounds(180, 590, 230, 60);
        frame.add(jButton1);

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("Pic/backpt2.png"))); // NOI18N
        jButton2.setText("jButton2");
        jButton2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 0, true));
        jButton2.addActionListener(this::jButton2ActionPerformed);
         jButton2.setBounds(630, 590, 240, 60);
        frame.add(jButton2);

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("Pic/search.png"))); // NOI18N
        jButton3.setText("jButton3");
        jButton3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 0));
        jButton3.addActionListener(this::jButton3ActionPerformed);
         jButton3.setBounds(660, 130, 150, 40);
        frame.add(jButton3);
        jTextField5.setBounds(420, 340, 210, 30);
        frame.add(jTextField5);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("Pic/HMSadmitpat.jpg"))); // NOI18N
        jLabel2.setText("jLabel2");
        jLabel2.setBounds(0, 0, 1000, 690);
        frame.add(jLabel2);

//        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
//        getContentPane().setLayout(layout);
//        layout.setHorizontalGroup(
//            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
//            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
//        );
//        layout.setVerticalGroup(
//            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
//            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
//        );

        pack();
        frame.setVisible(true);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
                        String ID=jTextField1.getText();
        try{
           
             String sql1 ="select * from `p` WHERE `id` ='"+ID+"'";
            PreparedStatement ptst1=conn.prepareCall(sql1);
            ResultSet rs= ptst1.executeQuery();
            if (jTextField1.getText().equals("")) {
                JOptionPane.showMessageDialog( frame, "Please enter Patient's id","Error", JOptionPane.ERROR_MESSAGE);
                return;
            }
           else {
            if(rs.next()){
            jTextField2.setText(rs.getString("name"));         
            jTextField3.setText(rs.getString("f_name"));      
            jTextField4.setText(rs.getString("days")); 
            }
            else{
                JOptionPane.showMessageDialog( frame, "No such record found","Error", JOptionPane.ERROR_MESSAGE);
            }
            }
        }
        catch(Exception e){
           JOptionPane.showMessageDialog(frame, e);
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        Addpatientroom obj = new Addpatientroom();
        obj.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
         String ID=jTextField1.getText();
         String room=jTextField5.getText();
         try{
                   
            String sql ="select * from `p` WHERE `id` ='"+ID+"'";
            PreparedStatement ptst=conn.prepareCall(sql);
            ResultSet rs= ptst.executeQuery();
            String sql1 ="select * from `room` WHERE `roomno` ='"+room+"'";
            PreparedStatement ptst1=conn.prepareCall(sql1);
            ResultSet rs1= ptst1.executeQuery();
                        if(rs.next()&&rs1.next()){
                             double costroom=rs1.getDouble("cost");
                             int days=rs.getInt("days");
                             double totalcost =costroom*days;
                            String sql2 ="Update `p` SET `cost`='"+totalcost+"'WHERE `id`='"+ID+"'";
                            String sql3 ="Update `p` SET `room`='"+room+"'WHERE `id`='"+ID+"'";
                             PreparedStatement ptst2 = conn.prepareStatement(sql2);
                             PreparedStatement ptst3 = conn.prepareStatement(sql3);
                            ptst2.executeUpdate();
                            ptst3.executeUpdate();
                             JOptionPane.showMessageDialog(frame, "Patient Admitted");
                        }
                        else{
                          JOptionPane.showMessageDialog( frame, "Something went wrong","Error", JOptionPane.ERROR_MESSAGE);
                return;
                        }
         
         }
         catch(Exception e){
           JOptionPane.showMessageDialog(frame, e);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        new Patientroom();
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Patientroom.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Patientroom.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Patientroom.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Patientroom.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                  
//            }
//        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    // End of variables declaration//GEN-END:variables
}
