
import java.sql.*;
import javax.swing.JFrame;
import javax.swing.JOptionPane;


/**
 *
 * @author Zainab
 */
public class Updatemed extends javax.swing.JFrame {
       JFrame frame;
    /**
     * Creates new form Updatemed
     */
    Connection conn = null;
    public Updatemed() {
        super("UpdateMed");
        initComponents();
        conn = Databaseconnection.connection();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        frame=new JFrame("Update/Delete");
        jPanel1 = new javax.swing.JPanel();
        search = new javax.swing.JButton();
        medid = new javax.swing.JTextField();
        medname = new javax.swing.JTextField();
        medprice = new javax.swing.JTextField();
        medquantity = new javax.swing.JTextField();
        medmfgdate = new javax.swing.JTextField();
        medexpdate = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        delete = new javax.swing.JButton();
        update = new javax.swing.JButton();
        back = new javax.swing.JButton();

//        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
//
//        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());


        frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        frame.setAlwaysOnTop(true);
        frame.setLocation(0, 0);
        frame.setSize(1200,1000);
        frame.setLayout(null);

        search.setBackground(new java.awt.Color(10, 153, 153));
        search.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        search.setForeground(new java.awt.Color(255, 255, 255));
        search.setText("SEARCH");
        search.addActionListener(this::searchActionPerformed);
        search.setBounds(710, 130, 100, 30);
        frame.add(search);

        medid.addActionListener(this::medidActionPerformed);
        medid.setBounds(390, 130, 260, 30);
        frame.add(medid);

        medname.addActionListener(this::mednameActionPerformed);
        
        medname.setBounds(390, 210, 260, 30);
        frame.add(medname);
        
        medprice.setBounds(390, 300, 260, 30);
        frame.add(medprice);
        medquantity.setBounds(390, 390, 260, 30);
        frame.add(medquantity);
        medmfgdate.setBounds(390, 480, 260, 30);
        frame.add(medmfgdate);
        medexpdate.setBounds(390, 570, 260, 30);
        frame.add(medexpdate);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("Pic/updatemed.jpg"))); // NOI18N
        jLabel1.setBounds(-1, -50, 1200, 900);
        frame.add(jLabel1);

        delete.setText("jButton1");
        delete.addActionListener(this::deleteActionPerformed);
         delete.setBounds(540, 650, 180, 40);
        frame.add(delete);

        update.setText("jButton1");
        update.addActionListener(this::updateActionPerformed);
        update.setBounds(320, 650, 180, 40);
        frame.add(update);

        back.setText("jButton1");
        back.addActionListener(this::backActionPerformed);
        back.setBounds(760, 650, 180, 40);
        frame.add(back);

//        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
//        getContentPane().setLayout(layout);
//        layout.setHorizontalGroup(
//            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
//            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
//        );
//        layout.setVerticalGroup(
//            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
//            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
//        );

        pack();
        frame.setVisible(true);
    }// </editor-fold>//GEN-END:initComponents

    private void medidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_medidActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_medidActionPerformed

    private void mednameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mednameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mednameActionPerformed

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        Pharmacy obj = new Pharmacy();
        obj.setVisible(true);
    }//GEN-LAST:event_backActionPerformed

    private void deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteActionPerformed
        // TODO add your handling code here:
        try{
            Statement stmt = conn.createStatement();
            int id = Integer.parseInt(medid.getText());
            // delete the data from pharmacy
            String sql = "DELETE FROM pharmacy WHERE medid = '"+id+"'";
            stmt.executeUpdate(sql);
            

            JOptionPane.showMessageDialog(frame,"Data is sucessfully deleted.");
            medid.setText("");
            medname.setText("");
            medprice.setText("");
            medquantity.setText("");
            medmfgdate.setText("");
            medexpdate.setText("");

        }catch(NumberFormatException | SQLException e){
            JOptionPane.showMessageDialog(frame,e);
        }
    }//GEN-LAST:event_deleteActionPerformed

    private void updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateActionPerformed
        // TODO add your handling code here:
        try{
            Statement stmt = conn.createStatement();
    
            
            int id = Integer.parseInt(medid.getText());
            String name = medname.getText();
            int price = Integer.parseInt(medprice.getText());
            int quantity = Integer.parseInt(medquantity.getText());
            String mfgdate = medmfgdate.getText();
            String expdate = medexpdate.getText();

            // update the data in pharmacy
            String sql = "UPDATE pharmacy SET medname = '"+name+"', medprice= '"+price+"', medquantity = '"+quantity+"',  medmfgdate = '"+mfgdate+"', medexpdate = '"+expdate+"'";
            stmt.executeUpdate(sql);
           
            

            JOptionPane.showMessageDialog(frame,"Data is sucessfully updated.");
            medid.setText("");
            medname.setText("");
            medprice.setText("");
            medquantity.setText("");
            medmfgdate.setText("");
            medexpdate.setText("");
            

        }catch(NumberFormatException | SQLException e){
            JOptionPane.showMessageDialog(frame,e);
        }
    }//GEN-LAST:event_updateActionPerformed

    private void searchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchActionPerformed
        // TODO add your handling code here:
        try{
            Statement stmt = conn.createStatement();
            int id = Integer.parseInt(medid.getText());
            String sql = "SELECT * FROM pharmacy WHERE medid = '"+id+"'";
            ResultSet rs = stmt.executeQuery(sql);
            if(rs.next()){
                medname.setText(rs.getString("medname"));
                medprice.setText(rs.getString("medprice"));
                medquantity.setText(rs.getString("medquantity"));
                medmfgdate.setText(rs.getString("medmfgdate"));
                medexpdate.setText(rs.getString("medexpdate"));
            }
            else{
                JOptionPane.showMessageDialog(frame,"Record Not Found");
            }

        }catch(NumberFormatException | SQLException e){
            JOptionPane.showMessageDialog(frame,e);
        }
    }//GEN-LAST:event_searchActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
         new Updatemed();
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Updatemed.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Updatemed.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Updatemed.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Updatemed.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                 
//            }
//        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton back;
    private javax.swing.JButton delete;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField medexpdate;
    private javax.swing.JTextField medid;
    private javax.swing.JTextField medmfgdate;
    private javax.swing.JTextField medname;
    private javax.swing.JTextField medprice;
    private javax.swing.JTextField medquantity;
    private javax.swing.JButton search;
    private javax.swing.JButton update;
    // End of variables declaration//GEN-END:variables
}